version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: docker
      dockerfile: nginx.dockerfile
    container_name: nginx-chickenpoll
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./storage/logs/xdebug.log:/var/log/xdebug.log
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql-chickenpoll
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: production
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  php:
    build:
      context: docker
      dockerfile: php.dockerfile
    container_name: php-chickenpoll
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel