require('../bootstrap');
require('./chart.js');
require('./dashboard.js');
require('./file-upload.js');
require('./hoverable-collapse.js');
require('./misc.js');
require('./off-canvas.js');
require('./todo.js');
require('./todolist.js');
